import {chromium,type Page} from 'playwright';
import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import market from '../data/markets/saudi-arabia.json' with {type:'json'};
import {createPlan} from './planner.js';
import type {AuditResult,Field,Locator,Finding,PassedCheck,FieldComparison,FieldEvidence} from './types.js';

const artifacts=path.resolve('artifacts');
const navigationTimeout=Number(process.env.NAVIGATION_TIMEOUT_MS||20000);
function cssEscape(value:string){return value.replace(/[^a-zA-Z0-9_-]/g,char=>`\\${char.codePointAt(0)!.toString(16)} `)}
function locatorCode(l:Locator){return l.strategy==='label'?`page.getByLabel(${JSON.stringify(l.value)})`:l.strategy==='role'?`page.getByRole('button', { name: ${JSON.stringify(l.value)} })`:l.strategy==='name'?`page.locator('[name=${JSON.stringify(l.value)}]')`:l.strategy==='id'?`page.locator('#${cssEscape(l.value)}')`:`page.locator(${JSON.stringify(l.value)})`;}
function testFor(url:string,title:string,locator:Locator,value:string,errorText:string){return `import { test, expect } from '@playwright/test';\n\ntest(${JSON.stringify(title)}, async ({ page }) => {\n  await page.goto(${JSON.stringify(url)});\n  const field = ${locatorCode(locator)};\n  await field.fill(${JSON.stringify(value)});\n  await field.blur();\n  await expect(field).toHaveValue(${JSON.stringify(value)});\n  await expect(page.getByText(${JSON.stringify(errorText)}, { exact: false })).not.toBeVisible();\n});\n`;}
async function inspect(page:Page):Promise<{fields:Field[];buttons:string[]}>{return page.evaluate(`(() => { const fields=[...document.querySelectorAll('input,textarea')].filter(el=>el instanceof HTMLInputElement&&el.type!=='hidden').map((el,index)=>{let label='';if(el.id){const direct=document.querySelector('label[for="'+CSS.escape(el.id)+'"]');if(direct&&direct.textContent)label=direct.textContent.trim()}if(!label)label=(el.closest('label')&&el.closest('label').textContent||el.getAttribute('aria-label')||'').trim();const locator=label?{strategy:'label',value:label}:el.name?{strategy:'name',value:el.name}:el.id?{strategy:'id',value:el.id}:{strategy:'css',value:'input:nth-of-type('+(index+1)+')'};return {tag:el.tagName.toLowerCase(),type:el.type||'text',label,name:el.name,placeholder:el.placeholder,required:el.required,locator}});const buttons=[...document.querySelectorAll('button,input[type=submit]')].map(el=>(el.textContent||el.value||'').trim()).filter(Boolean);return {fields,buttons}; })()`) as Promise<{fields:Field[];buttons:string[]}>}
async function fillByLocator(page:Page,l:Locator,value:string){const target=l.strategy==='label'?page.getByLabel(l.value).first():l.strategy==='name'?page.locator(`[name=${JSON.stringify(l.value)}]`).first():l.strategy==='id'?page.locator(`#${cssEscape(l.value)}`).first():page.locator(l.value).first();await target.fill(value);await target.blur();return target;}
async function clickByLocator(page:Page,l:Locator){const target=l.strategy==='role'?page.getByRole('button',{name:l.value}).first():l.strategy==='label'?page.getByLabel(l.value).first():l.strategy==='name'?page.locator(`[name=${JSON.stringify(l.value)}]`).first():l.strategy==='id'?page.locator(`#${cssEscape(l.value)}`).first():page.locator(l.value).first();await target.click();}
function caseDefinition(valueKey:string){
  if(valueKey==='fullName')return {rootCauseId:'name-ascii-only',checkId:'arabic-name',title:'Arabic and mixed-script names are rejected'};
  if(valueKey==='mixedName')return {rootCauseId:'name-ascii-only',checkId:'mixed-bidi',title:'Arabic and mixed-script names are rejected'};
  if(valueKey==='phoneLocal')return {rootCauseId:'phone-us-only',checkId:'phone-local',title:'Saudi phone formats are rejected'};
  if(valueKey==='phoneInternational')return {rootCauseId:'phone-us-only',checkId:'phone-international',title:'Saudi phone formats are rejected'};
  if(valueKey==='arabicIndicDigits')return {rootCauseId:'phone-us-only',checkId:'arabic-indic-digits',title:'Saudi phone formats are rejected'};
  return null;
}
const englishPersona:Record<string,string>={fullName:'John Smith',mixedName:'John Smith',email:'john.smith@example.com',phoneLocal:'+14155552671',phoneInternational:'+14155552671',city:'New York',password:'SafeDemo!2026',arabicIndicDigits:'+14155552671'};
async function measureFill(page:Page,locator:Locator,value:string):Promise<FieldEvidence>{
  const target=await fillByLocator(page,locator,value);const actual=await target.inputValue();const validationMessage=await target.evaluate(el=>{const described=el.getAttribute('aria-describedby');const node=described?document.getElementById(described):null;return node?.textContent?.trim()||(el as HTMLInputElement).validationMessage||''});
  return {value,actual,accepted:actual===value&&!validationMessage,validationMessage,locator};
}
export function classifyComparison(english:FieldEvidence,arabic:FieldEvidence):FieldComparison['classification']{
  if(arabic.accepted)return 'pass';
  return english.accepted?'market-specific':'general-form-issue';
}

export async function runAudit(url:URL,options:{allowSubmission:boolean;controlledBenchmark:boolean}):Promise<AuditResult>{
  await fs.mkdir(artifacts,{recursive:true});const id=crypto.randomUUID();const browser=await chromium.launch({headless:true});
  try{const englishContext=await browser.newContext({viewport:{width:1280,height:800},locale:'en-US'});const arabicContext=await browser.newContext({viewport:{width:1280,height:800},locale:'ar-SA'});const englishPage=await englishContext.newPage();const page=await arabicContext.newPage();for(const candidate of [englishPage,page])candidate.setDefaultTimeout(5000);await Promise.all([englishPage.goto(url.href,{waitUntil:'domcontentloaded',timeout:navigationTimeout}),page.goto(url.href,{waitUntil:'domcontentloaded',timeout:navigationTimeout})]);
    if(await page.locator('iframe[src*="captcha"], [class*="captcha" i], [id*="captcha" i]').count())return {status:'unsupported',verdict:'Unsupported site',url:url.href,planner:'not-invoked',fallbackReason:null,plannerLog:['Planner not invoked: CAPTCHA detected before DOM planning.'],allowSubmission:options.allowSubmission,benchmarkEvaluation:null,supportMessage:'CAPTCHA detected. This tool only supports public standard signup forms without CAPTCHA or authentication walls.',fields:[],plan:[],findings:[],passes:[],fieldComparisons:[],screenshots:{baseline:'',arabic:''},comparison:{english:'Not tested',arabic:'Not tested'}};
    const {fields,buttons}=await inspect(page);const plan=await createPlan(fields,buttons,options.allowSubmission);if(!plan.supported||fields.length===0){const supportMessage=fields.length===0?'No auditable signup fields were exposed to the deployed browser. The run was stopped instead of reporting a false pass.':plan.reason;return {status:'unsupported',verdict:'Unsupported site',url:url.href,planner:plan.source,fallbackReason:plan.fallbackReason,plannerLog:[...plan.log,`Graceful stop: ${supportMessage}`],allowSubmission:options.allowSubmission,benchmarkEvaluation:null,supportMessage,fields,plan:plan.actions,findings:[],passes:[],fieldComparisons:[],screenshots:{baseline:'',arabic:''},comparison:{english:'No standard form detected',arabic:'Not tested'}};}
    const baseline=`/artifacts/${id}-english.png`;const arabic=`/artifacts/${id}-arabic.png`;
    const executionLog=[...plan.log];const findingsByRoot=new Map<string,Finding>();const passes:PassedCheck[]=[];let submissionAttempted=false;let flowCompleted=false;
    const fieldComparisons:FieldComparison[]=[];
    for(const action of plan.actions){
      if(action.action==='click'){
        if(!options.allowSubmission){executionLog.push(`Execution skipped click: submission is not allowed for this target.`);continue;}
        try{submissionAttempted=true;await clickByLocator(page,action.locator);await page.waitForTimeout(150);flowCompleted=await page.locator('[data-audit-success="true"]').isVisible();executionLog.push(`Execution click: ${action.locator.strategy}=${action.locator.value}; flowCompleted=${flowCompleted}`);}catch(error){executionLog.push(`Execution click failed: ${error instanceof Error?error.message:'unknown click error'}`);}continue;
      }
      if(action.action!=='fill'||!action.valueKey)continue;const value=(market.persona as Record<string,string>)[action.valueKey];const englishValue=englishPersona[action.valueKey];if(!value||!englishValue){executionLog.push(`Execution skipped fill: unknown valueKey=${action.valueKey}`);continue;}
      try{const [englishEvidence,arabicEvidence]=await Promise.all([measureFill(englishPage,action.locator,englishValue),measureFill(page,action.locator,value)]);const definition=caseDefinition(action.valueKey);const classification=classifyComparison(englishEvidence,arabicEvidence);const checkId=definition?.checkId||action.valueKey;const fieldPurpose=action.locator.value||action.fieldPurpose||action.valueKey;fieldComparisons.push({checkId,fieldPurpose,valueKey:action.valueKey,classification,english:englishEvidence,arabic:arabicEvidence,evidence:{englishScreenshot:baseline,arabicScreenshot:arabic}});executionLog.push(`Execution comparison: valueKey=${action.valueKey}, locator=${action.locator.strategy}=${action.locator.value}, EN=${englishEvidence.accepted?'accepted':englishEvidence.validationMessage||'rejected'}, AR=${arabicEvidence.accepted?'accepted':arabicEvidence.validationMessage||'rejected'}, classification=${classification}`);if(!arabicEvidence.accepted&&definition){const marketSpecific=classification==='market-specific';const rootCauseId=marketSpecific?definition.rootCauseId:`general-${action.locator.strategy}-${action.locator.value}`;const existing=findingsByRoot.get(rootCauseId);const actual=arabicEvidence.validationMessage||arabicEvidence.actual;const testCase={checkId:definition.checkId,valueKey:action.valueKey,value,actual};if(existing){existing.testCases.push(testCase);}else{findingsByRoot.set(rootCauseId,{id:crypto.randomUUID(),rootCauseId,title:marketSpecific?definition.title:`General form issue in ${fieldPurpose}`,severity:'blocker',checkId:definition.checkId,summary:marketSpecific?(actual||'The Arabic value was rejected while the English control was accepted.'):`Both English and Arabic control values failed; this is not classified as market-specific.`,impact:marketSpecific?'A Saudi user may be unable to complete signup.':'The tested field appears broken for more than the Saudi persona.',actual,expected:marketSpecific?'Accept the Saudi value when the English control is accepted':'Accept a valid control value in at least one tested locale',locator:action.locator,evidenceScreenshot:arabic,generatedTest:testFor(url.href,definition.title,action.locator,value,actual||'invalid'),testCases:[testCase]});}}else if(definition){passes.push({checkId:definition.checkId,valueKey:action.valueKey,locator:action.locator,actual:arabicEvidence.actual});}
      }catch(error){executionLog.push(`Execution fill failed: valueKey=${action.valueKey}; ${error instanceof Error?error.message:'unknown fill error'}`);}}
    const findings=[...findingsByRoot.values()];
    await Promise.all([englishPage.screenshot({path:path.join(artifacts,`${id}-english.png`),fullPage:false}),page.screenshot({path:path.join(artifacts,`${id}-arabic.png`),fullPage:false})]);
    const failingTestCases=findings.reduce((total,finding)=>total+finding.testCases.length,0);const expectedRoots=new Set(['name-ascii-only','phone-us-only']);const detectedRoots=new Set(findings.map(finding=>finding.rootCauseId));const truePositives=[...detectedRoots].filter(root=>expectedRoots.has(root)).length;const falsePositives=[...detectedRoots].filter(root=>!expectedRoots.has(root)).length;const falseNegatives=[...expectedRoots].filter(root=>!detectedRoots.has(root)).length;const benchmarkEvaluation=options.controlledBenchmark?{groundTruthBlockers:2,detectedBlockers:findings.length,failingTestCases,truePositives,falsePositives,falseNegatives,precision:truePositives/(truePositives+falsePositives||1),recall:truePositives/(truePositives+falseNegatives||1),submissionAttempted,flowCompleted}:null;
    return {status:'completed',verdict:findings.length?`Found ${findings.length} unique blocker${findings.length===1?'':'s'} across ${failingTestCases} failing test cases`:`No blockers found in tested flows; ${passes.length} Saudi-market checks passed`,url:url.href,planner:plan.source,fallbackReason:plan.fallbackReason,plannerLog:executionLog,allowSubmission:options.allowSubmission,benchmarkEvaluation,fields,plan:plan.actions,findings,passes,fieldComparisons,screenshots:{baseline,arabic},comparison:{english:`English persona executed in isolated en-US context across ${fieldComparisons.length} field checks`,arabic:findings.length?'Saudi persona produced evidence-backed failures':'Tested Saudi persona inputs were preserved'}};
  }finally{await browser.close();}}
